- name: 'Install pre-requisites'
  ansible.builtin.apt:
    name:
      - default-jdk
      - default-jre
  become: true

- name: 'Create group for zookeeper'
  ansible.builtin.group:
    name: '{{ zk_group }}'
  become: true

- name: 'Create user account for zookeeper'
  ansible.builtin.user:
    name: '{{ zk_user }}'
    group: '{{ zk_group }}'
    comment: 'Zookeeper'
    shell: '/bin/bash'
  become: true

- name: 'Create data directory'
  ansible.builtin.file:
    path: '{{ zk_data_dir }}'
    state: 'directory'
    mode: '0755'
    owner: '{{ zk_user }}'
    group: '{{ zk_group }}'
  become: true

- name: 'Fetch and unarchive Zookeeper distribution'
  ansible.builtin.unarchive:
    src: '{{ zk_download_url }}'
    dest: '/opt'
    remote_src: true
  become: true

- name: 'Create a symbolic link to the versioned directory name'
  ansible.builtin.file:
    src: '/opt/apache-zookeeper-{{ zk_version }}-bin'
    dest: '{{ zk_install_dir }}'
    owner: '{{ zk_user }}'
    group: '{{ zk_group }}'
    state: 'link'
  become: true

- name: 'Template Zookeeper configuration file'
  ansible.builtin.template:
    src: zoo.cfg.j2
    dest: '{{ zk_install_dir }}/conf/zoo.cfg'
    owner: '{{ zk_user }}'
    group: '{{ zk_group }}'
    mode: '0644'
  become: true
  notify: zk reload

- name: 'Template Zookeeper myid file for node'
  ansible.builtin.template:
    src: zk.myid.j2
    dest: '{{ zk_data_dir }}/myid'
    mode: '0644'
    owner: '{{ zk_user }}'
    group: '{{ zk_group }}'
  become: true
  notify: zk reload

- name: 'Install Zookeeper systemd service'
  ansible.builtin.template:
    src: zk.service.j2
    dest: /etc/systemd/system/zk.service
    mode: '0644'
  become: true
  notify: systemctl daemon-reload

- name: 'Enabled Zookeeper systemd service'
  ansible.builtin.systemd:
    name: 'zk'
    state: 'started'
    enabled: true
    masked: false
  become: true
