all:
  children:
    zoo:
      hosts:
        zoo-a:
          ansible_host: zoo-a.skwar.xyz
        zoo-b:
          ansible_host: zoo-a.skwar.xyz
        zoo-c:
          ansible_host: zoo-a.skwar.xyz
