all:
  children:
    zoo:
      hosts:
        # Note: Need to use proper hostnames or IPs
        # Also might need to change the ansible_user name
        zoo-1:
          ansible_host: 20.199.190.180
          ansible_user: azureuser
        zoo-2:
          ansible_host: 20.199.184.82
          ansible_user: azureuser
        zoo-3:
          ansible_host: 20.199.189.52
          ansible_user: azureuser
