all:
  children:
    zoo:
      hosts:
        # Note: Need to use proper hostnames or IPs
        # Also might need to change the ansible_user name
        zoo-1:
          ansible_host: ec2-15-161-212-100.eu-south-1.compute.amazonaws.com
          ansible_user: ubuntu
        zoo-2:
          ansible_host: ec2-15-161-231-206.eu-south-1.compute.amazonaws.com
          ansible_user: ubuntu
        zoo-3:
          ansible_host: ec2-35-152-54-66.eu-south-1.compute.amazonaws.com
          ansible_user: ubuntu
