all:
  children:
    zoo:
      hosts:
        # Note: Need to use proper hostnames or IPs
        # Also might need to specify ansible_user name, if it's not "ansible"
        zoo-1:
          ansible_host: a.b.c.1
        zoo-2:
          ansible_host: a.b.c.2
        zoo-3:
          ansible_host: a.b.c.3
