zk_user: zk
zk_group: zk
zk_install_dir: /opt/zookeeper
zk_data_dir: /var/opt/zookeeper
zk_version: 3.7.0
zk_download_url: https://downloads.apache.org/zookeeper/zookeeper-3.7.0/apache-zookeeper-3.7.0-bin.tar.gz
