- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"
  become: yes

- name: sshd reload
  service:
    name: ssh
    state: reloaded
  when: ansible_service_mgr == "systemd"
  become: yes

- name: sshd restart
  service:
    name: ssh
    state: restarted
  when: ansible_service_mgr == "systemd"
  become: yes

- name: networking restart
  service:
    name: networking
    state: restarted
  when: ansible_service_mgr == "systemd"
  become: yes
