- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"
  become: yes

- name: zk reload
  service:
    name: zk
    state: reloaded
  when: ansible_service_mgr == "systemd"
  become: yes

- name: zk restart
  service:
    name: zk
    state: restarted
  when: ansible_service_mgr == "systemd"
  become: yes

