- name: 'systemctl daemon-reload'
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == "systemd"
  become: true

- name: 'zk reload'
  service:
    name: 'zk'
    state: 'reloaded'
  when: ansible_service_mgr == "systemd"
  become: true

- name: 'zk restart'
  service:
    name: 'zk'
    state: 'restarted'
  when: ansible_service_mgr == "systemd"
  become: true

